# Generated by Django 4.2.7 on 2023-12-26 21:28

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_recipe_ingredient_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_images'),
        ),
    ]
