# Generated by Django 4.2.7 on 2023-12-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_topic_image'),
        ('recipes', '0011_recipe_cropping_alter_recipe_image'),
    ]

    operations = [
    ]
