# Generated by Django 4.2.7 on 2023-12-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_merge_20231226_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_images/'),
        ),
    ]
