# Generated by Django 4.2.7 on 2023-12-26 21:46

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_delete_topic_remove_recipe_cropping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
